version: '3.8'

services:
  app:
    build: .
    container_name: php-fpm
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"
    networks:
      - app-network
    #Etablir la connexion avec MySQL
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Ag1805Sz0602@
      MYSQL_DATABASE: EcoRide
      MYSQL_USER: Amelie
      MYSQL_PASSWORD: Ag1805Sz0602@
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: db
      PMA_USER: Amelie
      PMA_PASSWORD: Ag1805Sz0602@
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:


